name: build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  golangci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: actions/checkout@v4
      - run: make lint
      - run: make test
      - run: make build
